version: "3.3"
services:
  mysqldb:
    image: "mysql:5.7"
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=picpayDB
      - MYSQL_USER=picpay
      - MYSQL_PASSWORD=picpay
      - MYSQL_ROOT_PASSWORD=picpay
    volumes:
      - "./create_database.sql:/docker-entrypoint-initdb.d/create_database.sql"
  spring-boot-app:
    build:
      context: "./"
      dockerfile: "Dockerfile"
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/picpayDB?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "picpay"
      SPRING_DATASOURCE_PASSWORD: "picpay"
    depends_on:
      - mysqldb